name: Run all tests

permissions:
  contents: write 

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version-file: '.nvmrc'

    - name: Install dependencies
      run: npm install
        
    - name: Run tests
      env:
        CI: true 
      run: npm run all

    - name: Upload Allure results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: ./allure-results  

    - name: Install Allure command-line tool
      run: npm install -g allure-commandline --save-dev

    - name: Generate Allure report
      run: allure generate ./allure-results --clean
    
    - name: Publish Allure report to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: ./allure-report  
        token: ${{ secrets.GITHUB_TOKEN }}
